### ISSUE TITLE
changing the name of the branch

### ISSUE THREAD

**Issue by 150balbes** [armbian/linux-rockchip#1]
I suggest changing the name of the branch and creating additional ones. As the main branch (which will be used to build stable official images), use more understandable and names, for example STABLE, STABLE-5.10 KERNEL-5.10 (these are only options for discussion and are not mandatory). An additional branch for testing NEXT, NEXT-5.10, KERNEL-NEXT, EDGE-5.10 (these are only options for discussion and are not mandatory). This branch is used to merge joint PRS from all participants for joint testing and is used to build night images.

**Comment by amazingfate** [comment]
We can decide a name as our develop branch. I put the first `linux-5.10-gen-rkr3.6` branch because this is the original source code from rockchip and we can take is as a reference. I will keep pushing new tags when rockchip has any updates.

**Comment by 150balbes** [comment]
Ok
It is advisable to hear the opinion of the other maintainers who plan to use this core. 
Do you know who else is working with this kernel?

**Comment by amazingfate** [comment]
I've updated rk35xx-legacy to use this kernel. But for rk3588 people are just using the kernel from the boards' vendors. Vendors can merge newer code from rockchip's internal repo to their branch, but this tag rkr3.6 should be the latest code we can get in public.

**Comment by amazingfate** [comment]
I just renamed the default branch name to `rockchip-5.10`, which is just a temporary name before we decide a more suitable name. The default branch should be our developing branch.
There is another branch `rockchip-sdk-5.10`, which will sync with rockchip's sdk code as a reference.
I also pushed to tags `linux-5.10-gen-rkr3.4` and `linux-5.10-gen-rkr3.6`

**Comment by 150balbes** [comment]
This suits me, if there are no objections from others, you can leave this name.

**Comment by 150balbes** [comment]
I propose to create an additional branch rockchip-5.10-next (The name is conditional and may be different) for input PR (for easy testing of the proposed changes). That is, PR is received. it is merged into a test branch, maintainers use this branch to build test versions and check the proposed changes. Changes to the rockchip-5.10 branch must be carried out strictly by the general agreement of all maintainers who use this core.

**Comment by amazingfate** [comment]
I agree with strict merge rule to the default branch. What is the difference between testing with branchs from developer's fork and testing with this repo?

**Comment by 150balbes** [comment]
> What is the difference between testing with branchs from developer's fork and testing with this repo?

Advantages of using a fixed branch with a fixed name. 
1. it is easy to use the same fixed branch name for quick switching (for example, in the settings file, it is enough just to uncomment the desired line, and after the test it is easy to go back to the stable version). 
2. you can combine several changes in the test branch at once, add corrections, change the code as  debug and add other PRS from other users. 
3. it is easy to track changes in the test branch with a banal command (git pull)

It's enough just to write to the maintainers that there are changes that need to be checked and the maintainers do not need to rack their brains and look for a branch with the right PR for testing.

**Comment by amazingfate** [comment]
I understand that you want a new branch as a cushion before the real merge. But there is something I'm worried about:
> you can combine several changes in the test branch at once, add corrections, change the code as debug and add other PRS from other users.

If that test branch havs received several changes, corrections or other PRs, when it's getting merged to the default branch, we can't make every commit atomic.
I hope every commit in the default branch atomic, so that when people come to see the code, they will get less confused.
If you are working on your own fork, you can do anything you want, even a reset or a force push, which is not that easy on this repo.
To add other people's commit, we can add his repo as a new remote and cherrypick commits, which should be not so hard.

**Comment by 150balbes** [comment]
> If that test branch havs received several changes, corrections or other PRs, when it's getting merged to the default branch, we can't make every commit atomic.
> I hope every commit in the default branch atomic, so that when people come to see the code, they will get less confused.
> If you are working on your own fork, you can do anything you want, even a reset or a force push, which is not that easy on this repo.
> To add other people's commit, we can add his repo as a new remote and cherrypick commits, which should be not so hard.

This is not the main core, where you need to have a "beautiful code with hotel and detailed PR". This core is designed to work well in Armbian. This is a temporary core until the necessary functions are obtained in the main core and there is no point in wasting time on it, the level is enough - it works as it is. It is enough that all changes are understood and approved by the maintainers. I'm not going to waste time on details for "hypothetical outsiders", if they need code - let them learn to read it, I don't want to waste my time (my money) on educational training and education of "outsiders". I repeat - there is no need for detailed and meticulous individual PR. I'm not going to make a benchmark out of this kernel, for me it's just a draft code that works "as is".
