### ISSUE TITLE
关于MV2100UZ1屏幕的支持问题

### ISSUE THREAD

**Issue by xinbiubiu** [armbian/linux-rockchip#102]
提交号：9cdbdccc8da08705fe1fe116ea84f7c219cc4d5f
疑问：请问这次提交是否经过实际验证？我的3588使用完全相同的屏幕和驱动IC，仿照此次提交进行修改并不能正常显示。
DSC的使用是否有相关注意事项，我是用的通路是vp2->dsc1->dsi1

**Comment by amazingfate** [comment]
Commit https://github.com/armbian/linux-rockchip/commit/9cdbdccc8da08705fe1fe116ea84f7c219cc4d5f is from rockchip's SDK, and this is not verified by armbian team. Please reach rockchip for help.
