### ISSUE TITLE
rebase from 5.10 to rockchip 6.1

### ISSUE THREAD

**Issue by amazingfate** [armbian/linux-rockchip#154]
@Joshua-Riek has done some rebase: https://github.com/Joshua-Riek/linux-rockchip/tree/rk-6.1-rkr1
I also did a rebase without building.
Here is the list of dropped patches:
| code module | commit name | drop reason |
| ---- | ---- | --- |
| rtl8852be wifi | https://github.com/armbian/linux-rockchip/commit/81c2a4ce71e4e0e912fb3d17cfdf570098844f5e | already supported by rtw89 |
| rtl8852bu wifi | https://github.com/armbian/linux-rockchip/commit/4699501901a5e0325fe789c4d8e4098cdc66dac6 |  |
| rtl8852be/u wifi | https://github.com/armbian/linux-rockchip/commit/a86585fbea3b84b71b87d4a655d2c5293aeafd56 |  |
| AX210 bt | https://github.com/armbian/linux-rockchip/commit/d425ee128eb94e1d455a2ad2d4481f0871f91a21 | already supported in 6.1 |
| rtl8821cs | https://github.com/armbian/linux-rockchip/commit/be5f28943310dec69d090a34342797f5b61f7af9 |  |
| rtl8821cs | https://github.com/armbian/linux-rockchip/commit/5df52303a36fdbbb2a19a4cdbb8e7d89f31c3dae |  |
| rtl8821cs | https://github.com/armbian/linux-rockchip/commit/c7596ba2cee145a9be953bede76f4e71f8ebdaf1 |  |
| rtl8821cs bt | https://github.com/armbian/linux-rockchip/commit/69ac97c70c5e9447c900b13b529421b3e8e8aa60 |  |
| iwlwifi pnvm | https://github.com/armbian/linux-rockchip/commit/1211e705126f7ddf1c1713d5aa0534f5ac6cd0ae | no need in 6.1 |
| stmmac VLAN | https://github.com/armbian/linux-rockchip/commit/dc87545ce727e0fdd4e15e9111a55d38b778c126 | already merged in 6.1 |
| rtl8852be bt | https://github.com/armbian/linux-rockchip/commit/0d05f8c90fbdcf35e63fa58c0d0400a19bc3a33f | already supported in 6.1 |
| khadas sound soc | https://github.com/armbian/linux-rockchip/commit/c608f287ef21fe0dbc7e0390cc45c21bf9f73b6b |  |
| revert khadas sound soc | https://github.com/armbian/linux-rockchip/commit/af7c34605fda3c6ed03869765cfa4fb84e90b73b |  |
| khadas mcu | https://github.com/armbian/linux-rockchip/commit/5d5bab7514e2ef3b0a0ffe7015e7e6f109e880af |  |
| khadas mcu | https://github.com/armbian/linux-rockchip/commit/d5f71e734110fbe394ac908fdfdc3da8a5bb6674 |  |
| khadas thermal | https://github.com/armbian/linux-rockchip/commit/4579d4440dbed64fad792c25c151c13c349c7b3c |  |
| khadas bt | https://github.com/armbian/linux-rockchip/commit/2b1cb9d3f6120333cb24a5143e26de1168a6284c |  |
| build *.dtbo | https://github.com/armbian/linux-rockchip/commit/7c622d095d168a706444bd4e88937a5b324ec550 | no need in 6.1 |
| update dtc | https://github.com/armbian/linux-rockchip/commit/f0fb25570af93e12cb8e832c859dd7c963018075 | no need in 6.1 |
| fix modpost | https://github.com/armbian/linux-rockchip/commit/3e2980446878c6bb4f41a0207687d8e4d0ecb41b | no need in 6.1 |
| usb gadget | https://github.com/armbian/linux-rockchip/commit/94d4102a30cdd4c99a391fd481c15ea23860b2cb | not necessary anymore |
| dma-buf for panfork | https://github.com/armbian/linux-rockchip/commit/4e4095c4ed4ad88feed39e851c797cbe6f7a9a2c | already merged in mainline 6.1 |
| dma-buf for panfork | https://github.com/armbian/linux-rockchip/commit/edb2457f29572efb0d5ef8331701dd4f6ccab937 | already merged in mainline 6.1 |
| dma-buf for panfork | https://github.com/armbian/linux-rockchip/commit/afbe8bc95e38dd5c90ef44bba8764ade4a882e2f | already merged in mainline 6.1 |
| drm for panfork | https://github.com/armbian/linux-rockchip/commit/04efbc6540c6c94180a587406de3aaa93765ae7b | no need in 6.1 |
| gt9xx touchscreen | https://github.com/armbian/linux-rockchip/commit/1e0050d30d7d2bd3f7cc952b9b184d9ff0adabfd | already supported |
| r8125 | https://github.com/armbian/linux-rockchip/commit/2944e15740e55b64f0a5dc40978acf929795ea2c | use mainline r8169 instead, discussion: https://github.com/awesometic/realtek-r8125-dkms/issues/48 |
| r8125 | https://github.com/armbian/linux-rockchip/commit/e28680f56381cbf302236790a2daeb0c9fefa89e |  |
| realtek pgtool | https://github.com/armbian/linux-rockchip/commit/2e74661fff6c991c146555d7cb27c114eb7ea2a5 | mainline already has it |
| uwe5622 wifi | https://github.com/armbian/linux-rockchip/commit/99e4151d6455f6985fe2b156a7baea003e062526 | since this is 6.1, we can use patches from armbian |
| spreadtrum bt for uwe5622 | https://github.com/armbian/linux-rockchip/commit/e05a708576e861af4bcea0e6d06fc7b2bf534530 | already in armbian's uwe5622 patch |  |
| aic8800 | https://github.com/armbian/linux-rockchip/commit/19c7c0dcdba1134fdeced79ac949da8ab26cb1a3 | reworked, add new driver from https://github.com/radxa-pkg/aic8800 |
| aic8800 | https://github.com/armbian/linux-rockchip/commit/c194463a2f13a62fbff3fb306d767f49fab581a8 | already included in above patch |
| aic8800 | https://github.com/armbian/linux-rockchip/commit/fa00435cdc0904a99202404189c55fa66fa94423 | already included in above patch |

**Comment by Joshua-Riek** [comment]
Hey! For panfork and wayland to work you need the below commits:

https://github.com/Joshua-Riek/linux-rockchip/commit/6ee34db111dddc085bb7f063367aa242f1f196f0
https://github.com/Joshua-Riek/linux-rockchip/commit/32fc58106ab6e03f60b062423b8148bc43ce030d
https://github.com/Joshua-Riek/linux-rockchip/commit/9e1e2c5cc83eff4339b34fb600e88a39563aba93

Btw do you have your 6.1 branch pushed?

**Comment by amazingfate** [comment]
My rebased code has not passed building. I will push it after it's built successfully and tested.

**Comment by amazingfate** [comment]
closed as pr is created: https://github.com/armbian/linux-rockchip/pull/155
