### ISSUE TITLE
Kernel and system questions

### ISSUE THREAD

**Issue by livelove1987** [armbian/linux-rockchip#199]
is this system just normal debian bookworm but with update kernel versions for NPU? also, whats RKNN Drivers version of latest img? Im planning on running it on Orange pi 5 plus because in orgianl software page for orange pi their version of Debian is not well up to date, and it's missing crucial updates ( like RKNN driver update )

**Comment by amazingfate** [comment]
This repo is modified kernel based on rockchip's sdk, which has two main versions: 5.10 and 6.1.
You can find version of rknpu from drivers/rknpu/include/rknpu_drv.h.
