### ISSUE TITLE
make: *** No rule to make target 'zImage'.

### ISSUE THREAD

**Issue by Czzqq** [armbian/linux-rockchip#208]
how to make a zImage? I ran the following commands and ended up with this printout.
`make rockchip_linux_defconfig` 
`make zImage`

**Comment by amazingfate** [comment]
It is not suppoted.

**Comment by igorpecovnik** [comment]
This is custom hardware world. Please use https://github.com/armbian/build to minimise troubles compiling firmware (kernel package). Every hardware has its own specialities and framework knows how to handle each.
