### ISSUE TITLE
Please add DTS for Orange Pi 3b v2.1

### ISSUE THREAD

**Issue by vlw** [armbian/linux-rockchip#216]
All new boards OPi 3b shipping with rev 2.1, our 'stable' branch for orange pi 3b is linux 6.1, but it's unbootable when eMMC connected even with wiped mtd0 (SPI). 

need cherry-pick this commit
https://github.com/orangepi-xunlong/linux-orangepi/commit/38dd4d9d9a1578f173912529bd587f63d7bd81e0

looks like uboot dts also need to be updated for detect revision
https://github.com/orangepi-xunlong/u-boot-orangepi/commit/0f7610abf7053e7b6cf9e7299aa1c0c1648efaa0

also fix for ethernet burn
https://github.com/orangepi-xunlong/u-boot-orangepi/commit/e525889e9d5994c9aa3acd2b73f477f4905cfc17

**Comment by igorpecovnik** [comment]
https://docs.armbian.com/Process_Contribute/
