### ISSUE TITLE
Kernel Panic Armbian_community_24.11.0-trunk.25_Orangepi3b_noble_vendor_6.1.75_gnome-kisak

### ISSUE THREAD

**Issue by defencedog** [armbian/linux-rockchip#228]
I am attaching my tty serial putty log. As usual **Orangepi-3b v2.1** doesn't work at all

[putty.log](https://github.com/user-attachments/files/16754528/putty.log)

**Comment by amazingfate** [comment]
This is issue of uboot https://github.com/armbian/build/pull/7025
