### ISSUE TITLE
Wayland Cursor Invisible [drm:vop2_plane_atomic_check] *ERROR*

### ISSUE THREAD

**Issue by defencedog** [armbian/linux-rockchip#229]
I have share detailed information on [armbian forums](https://forum.armbian.com/topic/44197-build-framework-patches-placement-for-orangepi-3b-v21/?do=findComment&comment=200197) but here is a concise stuff

My SBC is Opi3b v2.1 on `jammy` with `panfrost` enabled
Whether I install `ubuntu-desktop` or `armbian-gnome`; the cursor is invisible, however cursor works OK while logged in as `X-session` of Ubuntu meaning `wayland` is to blame. If you logged in KODI wayland session cursor works OK?? GDM3 has no cursor as well

When I move cursor while in wayland session, these errors keep repeating `journalctl -f`

```
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
 
```
I strongly believe its some GNOME related error. Internet is full of this bug when people are using eGPUs. If anyone has any idea, please help

**Comment by defencedog** [comment]
Similar error in @amazingfate [comment here](https://github.com/Joshua-Riek/ubuntu-rockchip/issues/89#issuecomment-1681722997)

**Comment by amazingfate** [comment]
I don't have the board to test. If you think it's an issue of gnome, you can try noble.
