### ISSUE TITLE
rtl8125 not detected on opi5plus with 6.1 kernel

### ISSUE THREAD

**Issue by amazingfate** [armbian/linux-rockchip#282]
After https://github.com/armbian/linux-rockchip/pull/221 is merged, rtl8125 ethernet is not detected.
We may need a special devicetree property for opi5plus to fix it.

**Comment by efectn** [comment]
I think other boards might be affected as well. 	Maybe link_up should only be existent for Rock 5 ITX?

**Comment by amazingfate** [comment]
The pr from radxa is similar with mainline driver: https://github.com/torvalds/linux/blob/v6.11/drivers/pci/controller/dwc/pcie-dw-rockchip.c#L175-L185, so I think what rock5itx is using should be the common case.
And I don't have a rk3588 board not detecting its rtl8125 ethernet.
