### ISSUE TITLE
Rock5b kernel panic on rkr4

### ISSUE THREAD

**Issue by lanefu** [armbian/linux-rockchip#68]
Built a fresh legacy kernel image yesterday and ran into this panic on startup.   Not sure where to debug from here

https://armbian.lane-fu.com/linx/w6aqntvw.txt

**Comment by amazingfate** [comment]
It seems to be npu related. What about disabling `rknpu` in the devicetree?

**Comment by lanefu** [comment]
i believe the board i was testing this on was defective... closing for now. will re-open if I'm able to reproduce on another device.
